application: musiclink-187719
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /tasks/(.+)
  script: main.app
  login: admin

- url: /
  static_files: app/index.html
  upload: app/index.html

libraries:
- name: webapp2
  version: "2.5.2"
